// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIT3PZJkMg4oe6KpGIQm9ft_NZM_zP23Y',
    appId: '1:1007263600702:web:4fd00ede5d4db71f2bc16f',
    messagingSenderId: '1007263600702',
    projectId: 'gsm-market-a1bf2',
    authDomain: 'gsm-market-a1bf2.firebaseapp.com',
    storageBucket: 'gsm-market-a1bf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwo3ye0qMVTCFwNkF5dRxqxu4pcoNAIg',
    appId: '1:1007263600702:android:e90ddc16ab76b3232bc16f',
    messagingSenderId: '1007263600702',
    projectId: 'gsm-market-a1bf2',
    storageBucket: 'gsm-market-a1bf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5eb51CmfNOQNKhy795SAHGvmZEbLXcVc',
    appId: '1:1007263600702:ios:c58672a4cdda85d32bc16f',
    messagingSenderId: '1007263600702',
    projectId: 'gsm-market-a1bf2',
    storageBucket: 'gsm-market-a1bf2.firebasestorage.app',
    iosBundleId: 'com.example.iosgsmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5eb51CmfNOQNKhy795SAHGvmZEbLXcVc',
    appId: '1:1007263600702:ios:c58672a4cdda85d32bc16f',
    messagingSenderId: '1007263600702',
    projectId: 'gsm-market-a1bf2',
    storageBucket: 'gsm-market-a1bf2.firebasestorage.app',
    iosBundleId: 'com.example.iosgsmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIT3PZJkMg4oe6KpGIQm9ft_NZM_zP23Y',
    appId: '1:1007263600702:web:26f956d4dcd3cba02bc16f',
    messagingSenderId: '1007263600702',
    projectId: 'gsm-market-a1bf2',
    authDomain: 'gsm-market-a1bf2.firebaseapp.com',
    storageBucket: 'gsm-market-a1bf2.firebasestorage.app',
  );
}
